### ISSUE TITLE
Limit the amount of messages retrieved initially

### ISSUE THREAD

**Issue by OtherwiseJunk** [jonnhy12333/hmct-web#14]
We should limit the number of messages we retrieve initially, X = 20 or something, and then retrieve in groups of X on scrolling to the "bottom"

**Comment by OtherwiseJunk** [comment]
Oh I'm an idiot you may already be doing this, I had set up a console.log on something and noticed it was still going after a while but I'm realizing that it just loops :V

**Comment by jonnhy12333** [comment]
yeah we do 100 initially now, hopefully that's okay
