### ISSUE TITLE
Retrieve messages on scroll

### ISSUE THREAD

**Issue by OtherwiseJunk** [jonnhy12333/hmct-web#44]
When I hit the top, I should get EVEN MORE messages. NEVER ENDING until it does.

**Comment by OtherwiseJunk** [comment]
We'll also need to make sure on mobile we're overwriting the pull down to refresh functionality. Prolly will do it on it's own but good to know for testing.

**Comment by jonnhy12333** [comment]
We now have a 'Get More Messages' button which takes care of this
