### ISSUE TITLE
The input field should change colors when a tag is active?

### ISSUE THREAD

**Issue by OtherwiseJunk** [jonnhy12333/hmct-web#70]
![image](https://user-images.githubusercontent.com/4574230/57538848-3dd01580-7317-11e9-81c9-9ee13103d8c2.png)
![image](https://user-images.githubusercontent.com/4574230/57538884-4d4f5e80-7317-11e9-87b2-848efceba658.png)

Should the input field here be blue because I have the #update tag selected?

**Comment by jonnhy12333** [comment]
We now display a chip of the current tag which shows the colors
