### ISSUE TITLE
Can you add flashing tab titles

### ISSUE THREAD

**Issue by houlematt** [jonnhy12333/hmct-web#75]

**Comment by OtherwiseJunk** [comment]
Just like have the *HMCT Web* text blink on and off?

**Comment by houlematt** [comment]
<img width="147" alt="image" src="https://user-images.githubusercontent.com/6727127/57632594-f8f2eb80-756f-11e9-85d9-8c691cbd946b.png">
Number of new messages like other sites have would be great

**Comment by OtherwiseJunk** [comment]
Modify the new message indicator to show a count of unread messages.
