### ISSUE TITLE
Have a new messages indicator

### ISSUE THREAD

**Issue by greggiannone** [jonnhy12333/hmct-web#86]
This could be some kind of line or marker where the division between unread and read messages are. This would also require the chat to stay with the old messages so the line isn't out of the window. A "jump to bottom" button might be useful as well.

**Comment by jonnhy12333** [comment]
Make sure you include all the messages! could be more than 40 or whatever the default is

**Comment by jonnhy12333** [comment]
This issue has been 'fixed' we have new message indicators
